import "@/styles/_globals.scss";
import { Inter } from "next/font/google";
import LayoutProvider from "@/Providers/LayoutProvider";
import { CookiesProvider } from "next-client-cookies/server";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className={inter.className}>
        <CookiesProvider>
          <LayoutProvider>{children}</LayoutProvider>
        </CookiesProvider>
      </body>
    </html>
  );
}
